/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>

class AABCSwap {
public:
  void solve(std::istream &in, std::ostream &out) {
    int X, Y, Z;
    in >> X >> Y >> Z;
    out << Z << " " << X << " " << Y;
  }
};


int main() {
	AABCSwap solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
