/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Kein Yukiyoshi
 */

#include "bits/stdc++.h"
#define int long long
#define FOR(i, a, b) for (int i = (int)(a); i < (int)(b); i++)
#define rep(i, n) for (int i = 0; i < (int)(n); i++)
#define ALL(obj) begin(obj), end(obj)
#define MAX(x) *max_element(ALL(x))
#define MIN(x) *min_element(ALL(x))
#define LOWER_BOUND(A, key) distance(A.begin(), lower_bound(ALL(A), key))
#define UPPER_BOUND(A, key) distance(A.begin(), upper_bound(ALL(A), key))
#define Endl endl

using namespace std;
using ll      = long long;
const int MOD = (int)(1e9 + 7);
const int INF = (int)(1e13 + 7);

int ceil_(int a, int b) { return (a + (b - 1)) / b; }
int positive_surplus(int &a) { return (a + MOD) % MOD; }
int bpm(int x, unsigned int y) {
  if (x == 0) return 0;
  if (y == 0) return 1;
  int ans   = 1;
  int digit = (int)((log((double)y) / log((double)2) / 1 + 1));
  x %= MOD;
  for (unsigned int i = 0; i < digit; i++) {
    if (((y >> i) & 1u) == 1) ans = ans * x % MOD;
    x = x * x % MOD;
  }
  return ans;
}
template <class T>
void cumulative_sum(T &container) {
  for (int i = 0; i < container.size() - 1; i++) container[i + 1] += container[i];
}
int N, M, Q;
int a[50];
int b[50];
int c[50];
int d[50];
int maxi = 0;
void calc(vector<int> &A) {
  int ret = 0;
  rep(i, Q) if (A[b[i] - 1] - A[a[i] - 1] == c[i]) ret += d[i];
  maxi = max(maxi, ret);
}

void with_replacement(vector<int> &A, int num) {
  if (num == N - 1) {
    calc(A);
  } else {
    FOR(i, A[num], M + 1) {
      A[num + 1] = i;
      with_replacement(A, num + 1);
    }
  }
}

class CManyRequirements {
public:
  static void solve(std::istream &cin, std::ostream &cout) {
    cin >> N >> M >> Q;
    rep(i, Q) {
      cin >> a[i];
      cin >> b[i];
      cin >> c[i];
      cin >> d[i];
    }
    FOR(i, 1, M + 1) {
      vector<int> A(N);
      A[0] = i;
      with_replacement(A, 0);
    }
    cout << maxi << endl;
  }
};


signed main() {
  CManyRequirements solver;
  std::istream& in(std::cin);
  std::ostream& out(std::cout);
  solver.solve(in, out);
  return 0;
}
