/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author KY2001
 */


#include "bits/stdc++.h"
#define int long long
#define For(i, a, b) for (int i = (int)(a); i < (int)(b); i++)
#define rep(i, n) for (int i = 0; i < (int)(n); i++)
#define ALL(obj) begin(obj), end(obj)
#define Max(x) *max_element(ALL(x))
#define Min(x) *min_element(ALL(x))
#define Lower_bound(A, key) distance(A.begin(), lower_bound(ALL(A), key))
#define Upper_bound(A, key) distance(A.begin(), upper_bound(ALL(A), key))

using namespace std;
using ll      = long long;
const int MOD = (int)(1e9 + 7);
const int INF = (int)(1e13 + 7);

int bpm(int x, int y) {
  if (x == 0)
    return 0;
  else if (y == 0) {
    return 1;
  }
  int ans = 1;
  x %= MOD;
  int digit = (int)((log((double)y) / log((double)2) / 1 + 1));
  for (int i = 0; i < digit; i++) {
    if (((y >> i) & 1u) == 1) {
      ans *= x;
      ans %= MOD;
    }
    x = x * x;
    x %= MOD;
  }
  return ans;
}


class CWriteAndErase {
public:
	int solve(std::istream& cin, std::ostream& cout) {
          int N;
          cin>>N;
          vector<int> A(N);
          rep(i, N){
            cin>>A[i];
          }
          sort(ALL(A));
          int ans = 0;
          int num = 1;
          if (N == 1){
            cout<<1<<endl;
            return 0;
          }
          For(i, 1, N){
            if (A[i] == A[i-1]){
              num += 1;
            }else{
              if (num%2){
                ans += 1;
              }
              num = 1;
            }
          }
          if (A[N-1] != A[N-2]){
            ans += 1;
          }
          cout<<ans<<endl;
	}
};


signed main() {
	CWriteAndErase solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
