/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Kein Yukiyoshi
 */

#include "bits/stdc++.h"
#define int long long
#define FOR(i, a, b) for (int i = (int)(a); i < (int)(b); i++)
#define rep(i, n) for (int i = 0; i < (int)(n); i++)
#define ALL(obj) begin(obj), end(obj)
#define MAX(x) *max_element(ALL(x))
#define MIN(x) *min_element(ALL(x))
#define LOWER_BOUND(A, key) distance(A.begin(), lower_bound(ALL(A), key))
#define UPPER_BOUND(A, key) distance(A.begin(), upper_bound(ALL(A), key))
#define Endl endl

using namespace std;
using ll      = long long;
const int MOD = (int)(1e9 + 7);
const int INF = (int)(1e13 + 7);

int ceil_(int a, int b) { return (a >= 0 ? (a + (b - 1)) / b : (a - (b - 1)) / b); }
int mod(int a, int b) { return a >= 0 ? a % b : a - (b * ceil_(a, b)); }
int bpm(int x, unsigned int y) {
  if (x == 0) return 0;
  if (y == 0) return 1;
  int ans   = 1;
  int digit = (int)((log((double)y) / log((double)2) / 1 + 1));
  x %= MOD;
  for (int i = 0; i < digit; i++) {
    if (((y >> i) & 1u) == 1) ans = ans * x % MOD;
    x = x * x % MOD;
  }
  return ans;
}
template <class T>
void cumulative_sum(T &container) {
  for (int i = 0; i < container.size() - 1; i++) container[i + 1] += container[i];
}

class DStringFormation {
public:
  static void solve(std::istream &cin, std::ostream &cout) {
    string S;
    cin >> S;
    int Q;
    cin >> Q;
    deque<char> ans;
    rep(i, S.size()) {
      ans.emplace_back(S[i]);
    }
    int direction = 1;
    rep(i, Q) {
      int Query;
      cin >> Query;
      if (Query == 1) {
        direction *= -1;
      } else {
        int F;
        char C;
        cin >> F >> C;
        if (direction == 1) {
          if (F == 1) {
            ans.emplace_front(C);
          } else {
            ans.emplace_back(C);
          }
        } else {
          if (F == 2) {
            ans.emplace_front(C);
          } else {
            ans.emplace_back(C);
          }
        };
      }
    }
    if (direction == 1) {
      rep(i, ans.size()) {
        cout << ans[i];
      }
    } else {
      rep(i, ans.size()) {
        cout << ans[ans.size() - 1 - i];
      }
    }
    cout << endl;
  }
};


signed main() {
  DStringFormation solver;
  std::istream& in(std::cin);
  std::ostream& out(std::cout);
  solver.solve(in, out);
  return 0;
}
