/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Kein Yukiyoshi
 */

#include "bits/stdc++.h"
#define int long long
#define FOR(i, a, b) for (int i = (int)(a); i < (int)(b); i++)
#define rep(i, n) for (int i = 0; i < (int)(n); i++)
#define ALL(obj) begin(obj), end(obj)
#define MAX(x) *max_element(ALL(x))
#define MIN(x) *min_element(ALL(x))
#define LOWER_BOUND(A, key) distance(A.begin(), lower_bound(ALL(A), key))
#define UPPER_BOUND(A, key) distance(A.begin(), upper_bound(ALL(A), key))
#define Endl endl

using namespace std;
using ll      = long long;
const int MOD = (int)(1e9 + 7);
const int INF = (int)(1e13 + 7);

int ceil_(int a, int b) { return (a + (b - 1)) / b; }
int positive_surplus(int &a) { return (a + MOD) % MOD; }
int bpm(int x, unsigned int y) {
  if (x == 0) return 0;
  if (y == 0) return 1;
  int ans   = 1;
  int digit = (int)((log((double)y) / log((double)2) / 1 + 1));
  x %= MOD;
  for (int i = 0; i < digit; i++) {
    if (((y >> i) & 1u) == 1) ans = ans * x % MOD;
    x = x * x % MOD;
  }
  return ans;
}
template <class T>
void cumulative_sum(T &container) {
  for (int i = 0; i < container.size() - 1; i++) container[i + 1] += container[i];
}
int factorial(int n) {
  int ans = 1;
  for (int i = 2; i <= n; i++) ans = ans * i % MOD;
  return ans;
}
class B {
public:
  static void solve(std::istream &cin, std::ostream &cout) {
    int N;
    cin >> N;
    deque<int> T(N);
    map<int, int> val_num;
    rep(i, N) {
      cin >> T[i];
      val_num[T[i]]++;
    }
    sort(ALL(T));
    int ans_time = 0;
    int ans      = 0;
    int now      = 0;
    ans += factorial(val_num[T[0]]);
    rep(i, N) {
      if (T.size() > 1) {
        if (T[1] != T[0]) {
          ans *= factorial(val_num[T[1]]);
          ans %= MOD;
        }
      }
      now += T[0];
      ans_time += now;
      T.pop_front();
    }
    cout << ans_time << endl;
    cout << ans % MOD << endl;
  }
};

signed main() {
  B solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
