/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Kein Yukiyoshi
 */

// clang-format off
//#pragma GCC optimize("Ofast")
//#pragma GCC target("avx")
#include <bits/stdc++.h>
using namespace std;
#define int long long
#define stoi stoll
#define Endl endl
#define itn int
#define fi first
#define se second
#define rep(i, n) for(int i=0, i##_len=(n); i<i##_len; i++)
#define rep2(i, a, b) for (int i = (int)(a), i##_len=(b); i < i##_len; i++)
#define rep3(i, a, b) for (int i = (int)(a), i##_len=(b); i >= i##_len; i--)
#define FOR(i, a) for (auto &i: a)
#define ALL(obj) begin(obj), end(obj)
#define _max(x) *max_element(ALL(x))
#define _min(x) *min_element(ALL(x))
#define _sum(x) accumulate(ALL(x), 0LL)
#define LOWER_BOUND(A, key) distance(begin(A), lower_bound(ALL(A), key))
#define UPPER_BOUND(A, key) distance(begin(A), upper_bound(ALL(A), key))

const int MOD   = 1000000007;
// const int MOD    = 998244353;
const int INF    = (int)(1e13 + 7);
const double EPS = 1e-14;
const double PI  = 3.14159265358979;
template <class T> using V = vector<T>;
template <class T> using VV = vector<vector<T>>;
template <class T> using VVV = vector<vector<vector<T>>>;
template <class T, class S>  using P = pair<T, S>;
template<class T> bool chmax(T &a, const T &b) {if (a < b) {a = b;return true;}return false;}
template<class T> bool chmin(T &a, const T &b) {if (b < a) {a = b;return true;}return false;}
int _ceil(int a, int b) { return (a >= 0 ? (a + (b - 1)) / b : (a - (b - 1)) / b); }
int _mod(int &a) {a = a >= 0 ? a % MOD : a - (MOD * _ceil(a, MOD));return a;}
int _pow(int a, int b) {int res = 1;for (a %= MOD; b; a = a * a % MOD, b >>= 1)if (b & 1) res = res * a % MOD;return res;}
// clang-format on

class D {
public:
  static void solve(istream &cin, ostream &cout) {
    cin.tie(nullptr);
    cout.tie(nullptr);
    ios::sync_with_stdio(false);
    cout << fixed << setprecision(15);
    int N;
    cin >> N;
    V<int> imos(24 * 60 + 3, 0);
    rep(i, N) {
      string data;
      cin >> data;
      int L = stoll(data.substr(0, 2)) * 60 + stoll(data.substr(2, 2)) - stoll(data.substr(2, 2)) % 5;
      imos[L]++;
      int R = stoll(data.substr(5, 2)) * 60 + stoll(data.substr(7, 2));
      if (stoll(data.substr(7, 2)) % 5 != 0) R += 5 - stoll(data.substr(7, 2)) % 5;
      imos[R + 1]--;
    }
    rep(i, 24 * 60 + 2) imos[i + 1] += imos[i];
    int L = 0;
    rep(i, 24 * 60 + 2) {
      if (imos[i] == 0 and imos[i + 1]) {
        L = i + 1;
      } else if (imos[i] and imos[i + 1] == 0) {
        string ans;
        if (L / 60 < 10) ans += '0';
        ans += to_string(L / 60);
        if (L % 60 < 10) ans += '0';
        ans += to_string(L % 60);
        ans += '-';
        if (i / 60 < 10) ans += '0';
        ans += to_string(i / 60);
        if (i % 60 < 10) ans += '0';
        ans += to_string(i % 60);
        cout << ans << endl;
      }
    }
  }
};


signed main() {
  D solver;
  std::istream& in(std::cin);
  std::ostream& out(std::cout);
  solver.solve(in, out);
  return 0;
}
