/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Kein Yukiyoshi
 */

#include "bits/stdc++.h"
#define int long long
#define FOR(i, a, b) for (int i = (int)(a); i < (int)(b); i++)
#define rep(i, n) for (int i = 0; i < (int)(n); i++)
#define ALL(obj) begin(obj), end(obj)
#define MAX(x) *max_element(ALL(x))
#define MIN(x) *min_element(ALL(x))
#define LOWER_BOUND(A, key) distance(A.begin(), lower_bound(ALL(A), key))
#define UPPER_BOUND(A, key) distance(A.begin(), upper_bound(ALL(A), key))
#define Endl endl

using namespace std;
using ll      = long long;
const int MOD = (int)(1e9 + 7);
const int INF = (int)(1e13 + 7);

int ceil_(int a, int b) { return (a >= 0 ? (a + (b - 1)) / b : (a - (b - 1)) / b); }
int mod(int a, int b) { return a >= 0 ? a % b : a - (b * ceil_(a, b)); }
int bpm(int x, unsigned int y) {
  if (x == 0) return 0;
  if (y == 0) return 1;
  int ans   = 1;
  int digit = (int)((log((double)y) / log((double)2) / 1 + 1));
  x %= MOD;
  for (int i = 0; i < digit; i++) {
    if (((y >> i) & 1u) == 1) ans = ans * x % MOD;
    x = x * x % MOD;
  }
  return ans;
}
template <class T>
void cumulative_sum(T &container) {
  for (int i = 0; i < container.size() - 1; i++) container[i + 1] += container[i];
}

class D {
public:
  static void solve(std::istream &cin, std::ostream &cout) {
    int H, W;
    cin >> H >> W;
    vector<string> S(H + 2);
    S[0] = string(W + 2, '#');
    rep(i, H) {
      string temp, temp2 = "#";
      cin >> temp;
      temp2 += temp + "#";
      S[i + 1] = temp2;
    }
    S[H + 1] = string(W + 2, '#');
    vector<vector<bool>> check(H, vector<bool>(W, false));
    vector<string> temp_S;
    FOR(i, 1, H + 1) {
      FOR(j, 1, W + 1) {
        if (S[i][j] == '#') {
          if (S[i + 1][j] == '#' and S[i - 1][j] == '#' and S[i][j + 1] == '#' and S[i][j - 1] == '#' and S[i + 1][j + 1] == '#' and S[i + 1][j - 1] == '#' and S[i - 1][j + 1] == '#' and S[i - 1][j - 1] == '#') {
            check[i - 1][j - 1] = true;
          }
        }
      }
    }
    rep(i, H) {
      rep(j, W) {
        if (check[i][j]) {
          i++;
          j++;
          S[i][j] = S[i + 1][j] = S[i - 1][j] = S[i][j + 1] = S[i][j - 1] = S[i + 1][j + 1] = S[i + 1][j - 1] = S[i - 1][j + 1] = S[i - 1][j - 1] = '.';
          i--;
          j--;
        }
      }
    }
    rep(i, H) {
      rep(j, W) {
        if (S[i + 1][j + 1] == '#') {
          cout << "impossible" << endl;
          return;
        }
      }
    }
    cout << "possible" << endl;
    rep(i, H) {
      string ans{};
      rep(j, W) {
        if (check[i][j]) {
          ans += "#";
        } else {
          ans += ".";
        }
      }
      cout << ans << endl;
    }
  }
};


signed main() {
  D solver;
  std::istream& in(std::cin);
  std::ostream& out(std::cout);
  solver.solve(in, out);
  return 0;
}
