/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Kein Yukiyoshi
 */

#include "bits/stdc++.h"
#define int long long
#define rep(i, n)           for (int i = 0; i < (int)(n); i++)
#define REP(i, a, b)        for (int i = (int)(a); i < (int)(b); i++)
#define FOR(i, a)           for (auto &i : a)
#define ALL(obj)            begin(obj), end(obj)
#define MAX(x)              *max_element(ALL(x))
#define MIN(x)              *min_element(ALL(x))
#define LOWER_BOUND(A, key) distance(A.begin(), lower_bound(ALL(A), key))
#define UPPER_BOUND(A, key) distance(A.begin(), upper_bound(ALL(A), key))
#define Endl                endl

using namespace std;
const int MOD    = (int)(1e9 + 7);
const int INF    = (int)(1e13 + 7);
const double EPS = 1e-14;
const double PI  = acos(-1);

int CEIL(int a, int b) { return (a >= 0 ? (a + (b - 1)) / b : (a - (b - 1)) / b); } //ceil() for int
int mod(int a, int b) { return a >= 0 ? a % b : a - (b * CEIL(a, b)); }             //always return positive num
int bpm(int x, int y) {                                                             //return x^y in order(log(y))
  if (x == 0) return 0;
  if (y == 0) return 1;
  int ans   = 1;
  int digit = (int)((log((double)y) / log((double)2) / 1 + 1));
  x %= MOD;
  for (int i = 0; i < digit; i++) {
    if (((y >> i) & 1u) == 1) ans = ans * x % MOD;
    x = x * x % MOD;
  }
  return ans;
}

class L {
public:
  static void solve(istream &cin, ostream &cout) {
    int N;
    cin >> N;
    vector<deque<int>> T(N);
    rep(i, N) {
      int K;
      cin >> K;
      T[i].assign(K, 0);
      rep(j, K) {
        cin >> T[i][j];
      }
    }
    map<int, int> one;
    map<int, int> two;
    map<int, int> ones;
    map<int, int> twos;
    rep(i, N) {
      one[T[i][0]] = i;
      ones[i]       = T[i][0];
      T[i].pop_front();
      if (T[i].size()) {
        two[T[i][0]] = i;
        twos[i]      = T[i][0];
        T[i].pop_front();
      }
    }
    int M;
    cin >> M;
    rep(_, M) {
      int a;
      cin >> a;
      int maxi1     = one.rbegin()->first;
      int maxi1_ind = one.rbegin()->second;
      int maxi2     = two.rbegin()->first;
      int maxi2_ind = two.rbegin()->second;
      if (a == 2 and maxi2 > maxi1) {
        cout << maxi2 << endl;
        two.erase(maxi2);
        twos.erase(maxi2_ind);
        if (T[maxi2_ind].size()) {
          two[T[maxi2_ind][0]] = maxi2_ind;
          twos[maxi2_ind]      = T[maxi2_ind][0];
          T[maxi2_ind].pop_front();
        }
      } else {
        cout << maxi1 << endl;
        one.erase(maxi1);
        ones.erase(maxi1_ind);
        if (twos.count(maxi1_ind)) {
          one[twos[maxi1_ind]] = maxi1_ind;
          ones[maxi1_ind]      = twos[maxi1_ind];
          two.erase(twos[maxi1_ind]);
          twos.erase(maxi1_ind);
          if (T[maxi1_ind].size()) {
            two[T[maxi1_ind][0]] = maxi1_ind;
            twos[maxi1_ind]      = T[maxi1_ind][0];
            T[maxi1_ind].pop_front();
          }
        }
      }
    }
  }
};


signed main() {
  cin.tie(0);
  cout.tie(0);
  ios_base::sync_with_stdio(false);
  cout<<fixed<<setprecison(15);
  L solver;
  std::istream& in(std::cin);
  std::ostream& out(std::cout);
  solver.solve(in, out);
  return 0;
}
</pre>

			<h4>
				Submission Info
				
			</h4>
			
			<div class="panel panel-default"><table class="table table-bordered table-striped">
				<tr>
					<th class="col-sm-4">Submission Time</th>
					<td class="text-center"><time class='fixtime fixtime-second'>2020-06-07 16:07:31+0900</time></td>
				</tr>
				<tr>
					<th>Task</th>
					<td class="text-center"><a href="/contests/past202005-open/tasks/past202005_l">L - Supamarket</a></td>
				</tr>
				<tr>
					<th>User</th>
					<td class="text-center"><a href="/users/KY2001">KY2001</a> <a href='/contests/past202005-open/submissions?f.User=KY2001'><span class='glyphicon glyphicon-search black' aria-hidden='true' data-toggle='tooltip' title='view KY2001's submissions'></span></a></td>
				</tr>
				<tr>
					<th>Language</th>
					<td class="text-center">C++ (GCC 9.2.1)</td>
				</tr>
				<tr>
					<th>Score</th>
					<td class="text-center">0</td>
				</tr>
				<tr>
					<th>Code Size</th>
					<td class="text-center">3393 Byte</td>
				</tr>
				<tr>
					<th>Status</th>
					<td id="judge-status" class="text-center"><span class='label label-warning' data-toggle='tooltip' data-placement='top' title="Compilation Error">CE</span></td>
				</tr>
				
			</table></div>

			
				<h4>Compile Error</h4>
				<pre>./Main.cpp: In function ‘int main()’:
./Main.cpp:111:16: error: ‘setprecison’ was not declared in this scope
  111 |   cout<<fixed<<setprecison(15);
      |                ^~~~~~~~~~~
