/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Kein Yukiyoshi
 */

#include "bits/stdc++.h"
#define int long long
#define rep(i, n)           for (int i = 0; i < (int)(n); i++)
#define REP(i, a, b)        for (int i = (int)(a); i < (int)(b); i++)
#define FOR(i, a)           for (auto &i : a)
#define ALL(obj)            begin(obj), end(obj)
#define MAX(x)              *max_element(ALL(x))
#define MIN(x)              *min_element(ALL(x))
#define LOWER_BOUND(A, key) distance(A.begin(), lower_bound(ALL(A), key))
#define UPPER_BOUND(A, key) distance(A.begin(), upper_bound(ALL(A), key))
#define Endl                endl

using namespace std;
const int MOD   = (int)(1e9 + 7);
const int INF   = (int)(1e13 + 7);
const double PI = acos(-1);

int CEIL(int a, int b) { return (a >= 0 ? (a + (b - 1)) / b : (a - (b - 1)) / b); } //ceil() for int
int mod(int a, int b) { return a >= 0 ? a % b : a - (b * CEIL(a, b)); }             //always return positive num
int bpm(int x, int y) {                                                             //return x^y in order(log(y))
  if (x == 0) return 0;
  if (y == 0) return 1;
  int ans   = 1;
  int digit = (int)((log((double)y) / log((double)2) / 1 + 1));
  x %= MOD;
  for (int i = 0; i < digit; i++) {
    if (((y >> i) & 1u) == 1) ans = ans * x % MOD;
    x = x * x % MOD;
  }
  return ans;
}
template <class T>
struct trio {
  T first{};
  T second{};
  T third{};
};
template <class T>
void cumulative_sum(T &container) {
  for (int i = 0; i < container.size() - 1; i++) container[i + 1] += container[i];
}

class K {
public:
  static void solve(istream &cin, ostream &cout) {
    int N, Q;
    cin >> N >> Q;
    vector<pair<int, int>> desk(N + 1, {-1, -1});      //下, 上
    vector<pair<int, int>> container(N + 1, {-1, -1}); // 下, 上
    rep(i, N) {
      desk[i + 1].first  = i + 1;
      desk[i + 1].second = i + 1;
    }
    rep(_, Q) {
      int f, t, x;
      cin >> f >> t >> x;
      if (container[x].first == -1) {
        desk[f].first                    = -1;
        container[x].first               = desk[t].second;
        if (desk[t].second != -1)
          container[desk[t].second].second = x;
        desk[t].second                   = desk[f].second;
        desk[f].second                   = -1;
        if (desk[t].first == -1) desk[t].first = x;
      } else {
        container[container[x].first].second = -1;
        if (desk[t].second != -1)
          container[desk[t].second].second = x;
        int tmp            = desk[f].second;
        desk[f].second     = container[x].first;
        container[x].first = desk[t].second;
        desk[t].second     = tmp;
        if (desk[t].first == -1) desk[t].first = x;
      }
    }
    vector<int> ans(N + 1);
    rep(i, N) {
      if (desk[i + 1].first != -1) {
        int tmp = desk[i + 1].first;
        while (true) {
          ans[tmp] = i + 1;
          if (container[tmp].second == -1) break;
          tmp = container[tmp].second;
        }
      }
    }
    rep(i, N) {
      cout << ans[i + 1] << endl;
    }
  }
};


signed main() {
  cin.tie(0);
  ios::sync_with_stdio(false);
  K solver;
  std::istream& in(std::cin);
  std::ostream& out(std::cout);
  solver.solve(in, out);
  return 0;
}
